# Generated by Django 3.2.25 on 2024-04-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_homo_studentsimilarity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homo_StudentSimilarity',
        ),
    ]
