# Generated by Django 4.1 on 2024-05-08 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0016_alter_community_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityJoinRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=20)),
                (
                    "approved_by",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approved_join_requests",
                        to="demo.student",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="demo.community",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="join_requests",
                        to="demo.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "community")},
            },
        ),
    ]
