# Generated by Django 4.1 on 2024-05-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0017_communityjoinrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField(default=1)),
                ("activity_id", models.BigIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("is_free", models.BooleanField(default=False)),
                ("is_optional", models.BooleanField(default=False)),
                ("start_time", models.BigIntegerField(default=0)),
                ("end_time", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("published", "已发布"),
                            ("unknown", "未知"),
                        ],
                        default="create",
                        max_length=255,
                    ),
                ),
                ("created_user_id", models.BigIntegerField()),
                ("created_time", models.BigIntegerField(default=0)),
                ("updated_time", models.BigIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="demo.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("chapter", "章节"),
                            ("unit", "单元"),
                            ("lesson", "课时"),
                            ("unknown", "未知"),
                        ],
                        max_length=255,
                    ),
                ),
                ("number", models.IntegerField()),
                ("seq", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("created_time", models.BigIntegerField()),
                ("updated_time", models.BigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unpublished", "草稿"),
                            ("published", "已发布"),
                            ("unknown", "未知"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_optional", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="demo.course",
                    ),
                ),
            ],
        ),
    ]
