# Generated by Django 4.2.13 on 2024-05-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo", "0018_coursetask_coursechapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursetask",
            name="type",
            field=models.CharField(
                choices=[
                    ("discuss", "讨论"),
                    ("doc", "完成文档"),
                    ("exercise", "实践"),
                    ("ppt", "ppt汇报"),
                    ("video", "视频任务"),
                    ("self", "自我完成"),
                    ("download", "需要下载"),
                    ("testpaper", "考试"),
                    ("homework", "课后作业"),
                    ("unknown", "未知"),
                ],
                default="unknown",
                max_length=255,
            ),
        ),
    ]
